### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by picklelv** [marcodejongh/chai-webdriverio#37]
We recently discovered that we were getting some false positives with the chai-webdriverio assertions.  If we didn't include the parenthesis, our tests would continue without failing.  Ouside the scope of chai-webdriverio?
```
.to.be.visible
```
instead of
```
.to.be.visible()
```

Also, the README shows 2 different ways to use `not`.  Which is correct?
```
.to.not.be.visible()
.not.to.have.text('property')
```

**Comment by mltsy** [comment]
I'll answer your second question first: You can put `.not` anywhere in the chain that sounds good to you :) It's just a flag that gets set for the final assertion.

As for leaving off the parenthesis, that is an issue with the new paradigm of "calling functions" without parenthesis, if you happen to access `visible` it in a context where `visible` is not defined, it will not cause an error, since `.visible` just returns `undefined`.   `.visible()` raises an exception, which is what you'd normally expect, so I would recommend always using the parenthesis.

There is talk about adding a `.dom` or other such accessor to prefix the method chain which would fix this issue, and make it fail even if you didn't use parenthesis, because `.dom` would be undefined, and trying to chain anything onto that would raise an exception.

I've added a new issue for this, in case you care to comment! https://github.com/marcodejongh/chai-webdriverio/issues/38
